arrowParens: always
bracketSpacing: true
endOfLine: auto
htmlWhitespaceSensitivity: css
printWidth: 120
proseWrap: preserve
quoteProps: as-needed
semi: true
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
vueIndentScriptAndStyle: true
rangeStart: 0
rangeEnd: 999999
overrides:
  - files: '*.json'
    options:
      printWidth: 200
      parser: json
  - files: '*.yml'
    options:
      printWidth: 200
      parser: yaml
  - files: '*.yaml'
    options:
      printWidth: 200
      parser: yaml
  - files: '*.md'
    options:
      parser: markdown
  - files: '*.html'
    options:
      parser: html
  - files: '*.css'
    options:
      parser: css
  - files: '*.scss'
    options:
      printWidth: 80
      parser: scss
  - files: '*.less'
    options:
      printWidth: 80
      parser: less
  - files: '*.ts'
    options:
      parser: typescript
  - files: '*.js'
    options:
      parser: babel
  - files: '*.cjs'
    options:
      parser: babel
  - files: '*.vue'
    options:
      printWidth: 120
      parser: vue
