name: qcalc
version: '0.11.2'
summary: A cross-platform calculator with unit conversion and currency exchange
description: |
  QCalc is a feature-rich calculator application supporting basic/advanced calculations,
  unit conversions, and real-time currency exchange rates. Built with Vue.js and Electron.

grade: devel
confinement: strict
base: core22
architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  qcalc:
    command: desktop-launch $SNAP/qcalc
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - opengl
      - x11
    environment:
      LC_NUMERIC: C.UTF-8
    desktop: usr/share/applications/qcalc.desktop

parts:
  qcalc:
    plugin: nil
    source: .
    override-build: |
      corepack enable
      yarn install
      quasar build -m electron -T linux
      mkdir -p $SNAPCRAFT_PART_INSTALL/qcalc
      cp -r dist/electron/Packaged/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/qcalc/
    build-packages:
      - nodejs
      - yarn
      - libgtk-3-0
      - libnotify4
      - libnss3
      - libxss1
      - libxtst6
      - xdg-utils
      - libatspi2.0-0
      - libuuid1
      - libappindicator3-1
    stage-packages:
      - libasound2
      - libgbm1
      - libxshmfence1

  gnome-platform:
    plugin: nil
    stage-packages:
      - gnome-platform
      - gnome-session
      - gsettings-desktop-schemas

slots:
  mpris:
    interface: mpris
    name: qcalc
