/**
 * @file CurrencyBaseData.ts
 * @description 이 파일은 통화 정보를 저장하는 상수 파일입니다.
 *              각 통화에 대한 설명과 기호를 포함하는 데이터를 정의하며,
 *              애플리케이션에서 통화 관련 기능을 구현하는 데 사용됩니다.
 *              통화 코드(예: 'USD', 'EUR')를 키로 사용하여 통화 정보를 관리합니다.
 */

/**
 * 통화 정보를 저장하는 인터페이스
 *
 * @interface Currency
 * @description
 * 이 인터페이스는 각 통화에 대한 정보를 저장합니다.
 * 키는 통화 코드(예: 'USD', 'EUR')이며, 값은 해당 통화의 설명과 기호를 포함하는 객체입니다.
 */
interface Currency {
  [currency: string]: {
    /** 통화의 설명 (예: 'United States Dollar') */
    desc: string;
    /** 통화의 기호 (예: '$') */
    symbol: string;
  };
}

/**
 * 통화 데이터를 저장하는 타입
 *
 * @type CurrencyData
 * @description
 * 이 타입은 Currency 인터페이스를 기반으로 하며,
 * 애플리케이션 전체에서 통화 정보를 일관되게 관리하는 데 사용됩니다.
 * 이를 통해 환율 변환, 통화 표시 등의 기능을 구현할 때 타입 안정성을 보장할 수 있습니다.
 */
export type CurrencyData = Currency;

// 환율에 대한 기본 데이터
export const currencyBaseData: CurrencyData = {
  '1INCH': { desc: '1inch', symbol: '1INCH' },
  AAVE: { desc: 'Aave', symbol: 'AAVE' },
  ADA: { desc: 'Cardano', symbol: 'ADA' },
  AED: { desc: 'United Arab Emirates Dirham', symbol: 'د.إ' },
  AFN: { desc: 'Afghan Afghani', symbol: '؋' },
  AGIX: { desc: 'SingularityNET', symbol: 'AGIX' },
  AKT: { desc: 'Akash Network', symbol: 'AKT' },
  ALGO: { desc: 'Algorand', symbol: 'ALGO' },
  ALL: { desc: 'Albanian Lek', symbol: 'L' },
  AMD: { desc: 'Armenian Dram', symbol: '֏' },
  AMP: { desc: 'Amp', symbol: 'AMP' },
  ANG: { desc: 'Netherlands Antillean Guilder', symbol: 'ƒ' },
  AOA: { desc: 'Angolan Kwanza', symbol: 'Kz' },
  APE: { desc: 'ApeCoin', symbol: 'APE' },
  APT: { desc: 'Aptos', symbol: 'APT' },
  AR: { desc: 'Arweave', symbol: 'AR' },
  ARB: { desc: 'Arbitrum', symbol: 'ARB' },
  ARS: { desc: 'Argentine Peso', symbol: '$' },
  ATOM: { desc: 'Cosmos', symbol: 'ATOM' },
  ATS: { desc: 'Austrian Schilling', symbol: 'öS' },
  AUD: { desc: 'Australian Dollar', symbol: 'A$' },
  AVAX: { desc: 'Avalanche', symbol: 'AVAX' },
  AWG: { desc: 'Aruban Florin', symbol: 'ƒ' },
  AXS: { desc: 'Axie Infinity', symbol: 'AXS' },
  AZM: { desc: 'Azerbaijani Manat (old)', symbol: 'AZM' },
  AZN: { desc: 'Azerbaijani Manat', symbol: '₼' },
  BAKE: { desc: 'BakeryToken', symbol: 'BAKE' },
  BAM: { desc: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM' },
  BAT: { desc: 'Basic Attention Token', symbol: 'BAT' },
  BBD: { desc: 'Barbadian Dollar', symbol: 'Bds$' },
  BCH: { desc: 'Bitcoin Cash', symbol: 'BCH' },
  BDT: { desc: 'Bangladeshi Taka', symbol: '৳' },
  BEF: { desc: 'Belgian Franc', symbol: 'BEF' },
  BGN: { desc: 'Bulgarian Lev', symbol: 'лв' },
  BHD: { desc: 'Bahraini Dinar', symbol: 'ب.د' },
  BIF: { desc: 'Burundian Franc', symbol: 'FBu' },
  BMD: { desc: 'Bermudan Dollar', symbol: 'BD$' },
  BNB: { desc: 'Binance Coin', symbol: 'BNB' },
  BND: { desc: 'Brunei Dollar', symbol: 'B$' },
  BOB: { desc: 'Bolivian Boliviano', symbol: 'Bs' },
  BRL: { desc: 'Brazilian Real', symbol: 'R$' },
  BSD: { desc: 'Bahamian Dollar', symbol: 'B$' },
  BSV: { desc: 'Bitcoin SV', symbol: 'BSV' },
  BSW: { desc: 'Biswap', symbol: 'BSW' },
  BTC: { desc: 'Bitcoin', symbol: '₿' },
  BTG: { desc: 'Bitcoin Gold', symbol: 'BTG' },
  BTN: { desc: 'Bhutanese Ngultrum', symbol: 'Nu.' },
  BTT: { desc: 'BitTorrent', symbol: 'BTT' },
  BUSD: { desc: 'Binance USD', symbol: 'BUSD' },
  BWP: { desc: 'Botswanan Pula', symbol: 'P' },
  BYN: { desc: 'New Belarusian Ruble', symbol: 'Br' },
  BYR: { desc: 'Belarusian Ruble', symbol: 'Br' },
  BZD: { desc: 'Belize Dollar', symbol: 'BZ$' },
  CAD: { desc: 'Canadian Dollar', symbol: 'CA$' },
  CAKE: { desc: 'PancakeSwap', symbol: 'CAKE' },
  CDF: { desc: 'Congolese Franc', symbol: 'FC' },
  CELO: { desc: 'Celo', symbol: 'CELO' },
  CFX: { desc: 'Conflux', symbol: 'CFX' },
  CHF: { desc: 'Swiss Franc', symbol: 'CHF' },
  CHZ: { desc: 'Chiliz', symbol: 'CHZ' },
  CLP: { desc: 'Chilean Peso', symbol: '$' },
  CNH: { desc: 'Chinese Yuan Offshore', symbol: '¥' },
  CNY: { desc: 'Chinese Yuan', symbol: '¥' },
  COMP: { desc: 'Compound', symbol: 'COMP' },
  COP: { desc: 'Colombian Peso', symbol: 'COL$' },
  CRC: { desc: 'Costa Rican Colón', symbol: '₡' },
  CRO: { desc: 'Cronos', symbol: 'CRO' },
  CRV: { desc: 'Curve DAO Token', symbol: 'CRV' },
  CSPR: { desc: 'Casper', symbol: 'CSPR' },
  CUC: { desc: 'Cuban Convertible Peso', symbol: '$' },
  CUP: { desc: 'Cuban Peso', symbol: '₱' },
  CVE: { desc: 'Cape Verdean Escudo', symbol: 'Esc' },
  CVX: { desc: 'Convex Finance', symbol: 'CVX' },
  CYP: { desc: 'Cypriot Pound', symbol: '£' },
  CZK: { desc: 'Czech Republic Koruna', symbol: 'Kč' },
  DAI: { desc: 'DAI Stablecoin', symbol: 'DAI' },
  DASH: { desc: 'Dash', symbol: 'DASH' },
  DCR: { desc: 'Decred', symbol: 'DCR' },
  DEM: { desc: 'German Mark', symbol: 'DM' },
  DFI: { desc: 'DeFiChain', symbol: 'DFI' },
  DJF: { desc: 'Djiboutian Franc', symbol: 'Fdj' },
  DKK: { desc: 'Danish Krone', symbol: 'kr' },
  DOGE: { desc: 'Dogecoin', symbol: 'Ð' },
  DOP: { desc: 'Dominican Peso', symbol: 'RD$' },
  DOT: { desc: 'Polkadot', symbol: 'DOT' },
  DYDX: { desc: 'dYdX', symbol: 'DYDX' },
  DZD: { desc: 'Algerian Dinar', symbol: 'د.ج' },
  EEK: { desc: 'Estonian Kroon', symbol: 'EEK' },
  EGLD: { desc: 'MultiversX', symbol: 'EGLD' },
  EGP: { desc: 'Egyptian Pound', symbol: '£' },
  ENJ: { desc: 'Enjin Coin', symbol: 'ENJ' },
  EOS: { desc: 'EOS', symbol: 'EOS' },
  ERN: { desc: 'Eritrean Nakfa', symbol: 'Nfk' },
  ESP: { desc: 'Spanish Peseta', symbol: '₧' },
  ETB: { desc: 'Ethiopian Birr', symbol: 'Br' },
  ETC: { desc: 'Ethereum Classic', symbol: 'ETC' },
  ETH: { desc: 'Ethereum', symbol: 'Ξ' },
  EUR: { desc: 'Euro', symbol: '€' },
  EURC: { desc: 'Euro Coin', symbol: 'EURC' },
  FEI: { desc: 'Fei USD', symbol: 'FEI' },
  FIL: { desc: 'Filecoin', symbol: 'FIL' },
  FIM: { desc: 'Finnish Markka', symbol: 'mk' },
  FJD: { desc: 'Fijian Dollar', symbol: 'FJ$' },
  FKP: { desc: 'Falkland Islands Pound', symbol: '£' },
  FLOW: { desc: 'Flow', symbol: 'FLOW' },
  FLR: { desc: 'Flare', symbol: 'FLR' },
  FRAX: { desc: 'Frax', symbol: 'FRAX' },
  FRF: { desc: 'French Franc', symbol: 'F' },
  FTT: { desc: 'FTX Token', symbol: 'FTT' },
  GALA: { desc: 'Gala', symbol: 'GALA' },
  GBP: { desc: 'British Pound Sterling', symbol: '£' },
  GEL: { desc: 'Georgian Lari', symbol: '₾' },
  GGP: { desc: 'Guernsey Pound', symbol: '£' },
  GHC: { desc: 'Ghanaian Cedi (old)', symbol: '₵' },
  GHS: { desc: 'Ghanaian Cedi', symbol: 'GH₵' },
  GIP: { desc: 'Gibraltar Pound', symbol: '£' },
  GMD: { desc: 'Gambian Dalasi', symbol: 'D' },
  GMX: { desc: 'GMX', symbol: 'GMX' },
  GNF: { desc: 'Guinean Franc', symbol: 'FG' },
  GNO: { desc: 'Gnosis', symbol: 'GNO' },
  GRD: { desc: 'Greek Drachma', symbol: '₯' },
  GRT: { desc: 'The Graph', symbol: 'GRT' },
  GT: { desc: 'GateToken', symbol: 'GT' },
  GTQ: { desc: 'Guatemalan Quetzal', symbol: 'Q' },
  GUSD: { desc: 'Gemini Dollar', symbol: 'GUSD' },
  GYD: { desc: 'Guyanaese Dollar', symbol: 'GY$' },
  HBAR: { desc: 'Hedera', symbol: 'ℏ' },
  HKD: { desc: 'Hong Kong Dollar', symbol: 'HK$' },
  HNL: { desc: 'Honduran Lempira', symbol: 'L' },
  HNT: { desc: 'Helium', symbol: 'HNT' },
  HOT: { desc: 'Holo', symbol: 'HOT' },
  HRK: { desc: 'Croatian Kuna', symbol: 'kn' },
  HT: { desc: 'Huobi Token', symbol: 'HT' },
  HTG: { desc: 'Haitian Gourde', symbol: 'G' },
  HUF: { desc: 'Hungarian Forint', symbol: 'Ft' },
  ICP: { desc: 'Internet Computer', symbol: 'ICP' },
  IDR: { desc: 'Indonesian Rupiah', symbol: 'Rp' },
  IEP: { desc: 'Irish Pound', symbol: 'IR£' },
  ILS: { desc: 'Israeli New Sheqel', symbol: '₪' },
  IMP: { desc: 'Manx Pound', symbol: '£' },
  IMX: { desc: 'Immutable X', symbol: 'IMX' },
  INJ: { desc: 'Injective', symbol: 'INJ' },
  INR: { desc: 'Indian Rupee', symbol: '₹' },
  IQD: { desc: 'Iraqi Dinar', symbol: 'ع.د' },
  IRR: { desc: 'Iranian Rial', symbol: '﷼' },
  ISK: { desc: 'Icelandic Króna', symbol: 'kr' },
  ITL: { desc: 'Italian Lira', symbol: '₤' },
  JEP: { desc: 'Jersey Pound', symbol: '£' },
  JMD: { desc: 'Jamaican Dollar', symbol: 'J$' },
  JOD: { desc: 'Jordanian Dinar', symbol: 'د.ا' },
  JPY: { desc: 'Japanese Yen', symbol: '¥' },
  KAS: { desc: 'Kaspa', symbol: 'KAS' },
  KAVA: { desc: 'Kava', symbol: 'KAVA' },
  KCS: { desc: 'KuCoin Token', symbol: 'KCS' },
  KDA: { desc: 'Kadena', symbol: 'KDA' },
  KES: { desc: 'Kenyan Shilling', symbol: 'KSh' },
  KGS: { desc: 'Kyrgystani Som', symbol: 'с' },
  KHR: { desc: 'Cambodian Riel', symbol: '៛' },
  KMF: { desc: 'Comorian Franc', symbol: 'CF' },
  KNC: { desc: 'Kyber Network', symbol: 'KNC' },
  KPW: { desc: 'North Korean Won', symbol: '₩' },
  KRW: { desc: 'South Korean Won', symbol: '₩' },
  KSM: { desc: 'Kusama', symbol: 'KSM' },
  KWD: { desc: 'Kuwaiti Dinar', symbol: 'د.ك' },
  KYD: { desc: 'Cayman Islands Dollar', symbol: 'CI$' },
  KZT: { desc: 'Kazakhstani Tenge', symbol: '₸' },
  LAK: { desc: 'Laotian Kip', symbol: '₭' },
  LBP: { desc: 'Lebanese Pound', symbol: 'ل.ل' },
  LDO: { desc: 'Lido DAO', symbol: 'LDO' },
  LEO: { desc: 'UNUS SED LEO', symbol: 'LEO' },
  LINK: { desc: 'Chainlink', symbol: 'LINK' },
  LKR: { desc: 'Sri Lankan Rupee', symbol: '₨' },
  LRC: { desc: 'Loopring', symbol: 'LRC' },
  LRD: { desc: 'Liberian Dollar', symbol: 'L$' },
  LSL: { desc: 'Lesotho Loti', symbol: 'L' },
  LTC: { desc: 'Litecoin', symbol: 'Ł' },
  LTL: { desc: 'Lithuanian Litas', symbol: 'Lt' },
  LUF: { desc: 'Luxembourg Franc', symbol: 'LUF' },
  LUNA: { desc: 'Terra', symbol: 'LUNA' },
  LUNC: { desc: 'Terra Classic', symbol: 'LUNC' },
  LVL: { desc: 'Latvian Lats', symbol: 'Ls' },
  LYD: { desc: 'Libyan Dinar', symbol: 'ل.د' },
  MAD: { desc: 'Moroccan Dirham', symbol: 'د.م.' },
  MANA: { desc: 'Decentraland', symbol: 'MANA' },
  MBX: { desc: 'MARBLEX', symbol: 'MBX' },
  MDL: { desc: 'Moldovan Leu', symbol: 'L' },
  MGA: { desc: 'Malagasy Ariary', symbol: 'Ar' },
  MGF: { desc: 'Malagasy Franc', symbol: 'MGF' },
  MINA: { desc: 'Mina Protocol', symbol: 'MINA' },
  MKD: { desc: 'Macedonian Denar', symbol: 'ден' },
  MKR: { desc: 'Maker', symbol: 'MKR' },
  MMK: { desc: 'Myanma Kyat', symbol: 'K' },
  MNT: { desc: 'Mongolian Tugrik', symbol: '₮' },
  MOP: { desc: 'Macanese Pataca', symbol: 'MOP$' },
  MRO: { desc: 'Mauritanian Ouguiya', symbol: 'UM' },
  MRU: { desc: 'Mauritanian Ouguiya', symbol: 'UM' },
  MTL: { desc: 'Maltese Lira', symbol: 'Lm' },
  MUR: { desc: 'Mauritian Rupee', symbol: '₨' },
  MVR: { desc: 'Maldivian Rufiyaa', symbol: 'Rf' },
  MWK: { desc: 'Malawian Kwacha', symbol: 'MK' },
  MXN: { desc: 'Mexican Peso', symbol: 'MX$' },
  MXV: { desc: 'Mexican Unidad de Inversion', symbol: 'MXV' },
  MYR: { desc: 'Malaysian Ringgit', symbol: 'RM' },
  MZM: { desc: 'Mozambican Metical (old)', symbol: 'MZM' },
  MZN: { desc: 'Mozambican Metical', symbol: 'MT' },
  NAD: { desc: 'Namibian Dollar', symbol: 'N$' },
  NEAR: { desc: 'NEAR Protocol', symbol: 'NEAR' },
  NEO: { desc: 'NEO', symbol: 'NEO' },
  NEXO: { desc: 'Nexo', symbol: 'NEXO' },
  NFT: { desc: 'APENFT', symbol: 'NFT' },
  NGN: { desc: 'Nigerian Naira', symbol: '₦' },
  NIO: { desc: 'Nicaraguan Córdoba', symbol: 'C$' },
  NLG: { desc: 'Dutch Guilder', symbol: 'ƒ' },
  NOK: { desc: 'Norwegian Krone', symbol: 'kr' },
  NPR: { desc: 'Nepalese Rupee', symbol: '₨' },
  NZD: { desc: 'New Zealand Dollar', symbol: 'NZ$' },
  OKB: { desc: 'OKB', symbol: 'OKB' },
  OMR: { desc: 'Omani Rial', symbol: 'ر.ع.' },
  ONE: { desc: 'Harmony', symbol: 'ONE' },
  OP: { desc: 'Optimism', symbol: 'OP' },
  ORDI: { desc: 'ORDI', symbol: 'ORDI' },
  PAB: { desc: 'Panamanian Balboa', symbol: 'B/.' },
  PAXG: { desc: 'PAX Gold', symbol: 'PAXG' },
  PEN: { desc: 'Peruvian Nuevo Sol', symbol: 'S/.' },
  PEPE: { desc: 'Pepe', symbol: 'PEPE' },
  PGK: { desc: 'Papua New Guinean Kina', symbol: 'K' },
  PHP: { desc: 'Philippine Peso', symbol: '₱' },
  PI: { desc: 'Pi Network', symbol: 'PI' },
  PKR: { desc: 'Pakistani Rupee', symbol: '₨' },
  PLN: { desc: 'Polish Zloty', symbol: 'zł' },
  POL: { desc: 'Polygon', symbol: 'POL' },
  PTE: { desc: 'Portuguese Escudo', symbol: 'PTE' },
  PYG: { desc: 'Paraguayan Guarani', symbol: '₲' },
  QAR: { desc: 'Qatari Rial', symbol: '﷼' },
  QNT: { desc: 'Quant', symbol: 'QNT' },
  QTUM: { desc: 'Qtum', symbol: 'QTUM' },
  ROL: { desc: 'Romanian Leu (old)', symbol: 'ROL' },
  RON: { desc: 'Romanian Leu', symbol: 'lei' },
  RPL: { desc: 'Rocket Pool', symbol: 'RPL' },
  RSD: { desc: 'Serbian Dinar', symbol: 'дін.' },
  RUB: { desc: 'Russian Ruble', symbol: '₽' },
  RUNE: { desc: 'THORChain', symbol: 'RUNE' },
  RVN: { desc: 'Ravencoin', symbol: 'RVN' },
  RWF: { desc: 'Rwandan Franc', symbol: 'FRw' },
  SAND: { desc: 'The Sandbox', symbol: 'SAND' },
  SAR: { desc: 'Saudi Riyal', symbol: '﷼' },
  SBD: { desc: 'Solomon Islands Dollar', symbol: 'SI$' },
  SCR: { desc: 'Seychellois Rupee', symbol: '₨' },
  SDD: { desc: 'Sudanese Dinar', symbol: 'SDD' },
  SDG: { desc: 'Sudanese Pound', symbol: 'ج.س.' },
  SEK: { desc: 'Swedish Krona', symbol: 'kr' },
  SGD: { desc: 'Singapore Dollar', symbol: 'S$' },
  SHIB: { desc: 'Shiba Inu', symbol: 'SHIB' },
  SHP: { desc: 'Saint Helena Pound', symbol: '£' },
  SIT: { desc: 'Slovenian Tolar', symbol: 'SIT' },
  SKK: { desc: 'Slovak Koruna', symbol: 'Sk' },
  SLE: { desc: 'Sierra Leonean Leone', symbol: 'Le' },
  SLL: { desc: 'Sierra Leonean Leone', symbol: 'Le' },
  SNX: { desc: 'Synthetix', symbol: 'SNX' },
  SOL: { desc: 'Solana', symbol: 'SOL' },
  SOS: { desc: 'Somali Shilling', symbol: 'S' },
  SPL: { desc: 'Seborgan Luigino', symbol: 'SPL' },
  SRD: { desc: 'Surinamese Dollar', symbol: 'SR$' },
  SRG: { desc: 'Surinamese Guilder', symbol: 'SRG' },
  SSP: { desc: 'South Sudanese Pound', symbol: '£' },
  STD: { desc: 'São Tomé and Príncipe Dobra', symbol: 'Db' },
  STN: { desc: 'São Tomé and Príncipe Dobra', symbol: 'Db' },
  STX: { desc: 'Stacks', symbol: 'STX' },
  SUI: { desc: 'Sui', symbol: 'SUI' },
  SVC: { desc: 'Salvadoran Colón', symbol: '$' },
  SYP: { desc: 'Syrian Pound', symbol: '£' },
  SZL: { desc: 'Swazi Lilangeni', symbol: 'E' },
  THB: { desc: 'Thai Baht', symbol: '฿' },
  THETA: { desc: 'Theta Network', symbol: 'THETA' },
  TJS: { desc: 'Tajikistani Somoni', symbol: 'TJS' },
  TMM: { desc: 'Turkmenistani Manat (old)', symbol: 'TMM' },
  TMT: { desc: 'Turkmenistani Manat', symbol: 'TMT' },
  TND: { desc: 'Tunisian Dinar', symbol: 'TND' },
  TON: { desc: 'Toncoin', symbol: 'TON' },
  TOP: { desc: "Tongan Pa'anga", symbol: 'TOP' },
  TRL: { desc: 'Turkish Lira (old)', symbol: 'TRL' },
  TRX: { desc: 'TRON', symbol: 'TRX' },
  TRY: { desc: 'Turkish Lira', symbol: 'TRY' },
  TTD: { desc: 'Trinidad and Tobago Dollar', symbol: 'TT$' },
  TUSD: { desc: 'TrueUSD', symbol: 'TUSD' },
  TVD: { desc: 'Tuvaluan Dollar', symbol: '$' },
  TWD: { desc: 'New Taiwan Dollar', symbol: 'NT$' },
  TWT: { desc: 'Trust Wallet Token', symbol: 'TWT' },
  TZS: { desc: 'Tanzanian Shilling', symbol: 'TZS' },
  UAH: { desc: 'Ukrainian Hryvnia', symbol: '₴' },
  UGX: { desc: 'Ugandan Shilling', symbol: 'UGX' },
  UNI: { desc: 'Uniswap', symbol: 'UNI' },
  USD: { desc: 'United States Dollar', symbol: '$' },
  USDC: { desc: 'USD Coin', symbol: 'USDC' },
  USDD: { desc: 'USDD', symbol: 'USDD' },
  USDP: { desc: 'Pax Dollar', symbol: 'USDP' },
  USDT: { desc: 'Tether', symbol: '₮' },
  UYU: { desc: 'Uruguayan Peso', symbol: 'UY$' },
  UZS: { desc: 'Uzbekistan Som', symbol: 'UZS' },
  VAL: { desc: 'Vatican Lira', symbol: 'VAL' },
  VEB: { desc: 'Venezuelan Bolívar (old)', symbol: 'VEB' },
  VED: { desc: 'Venezuelan Digital Bolívar', symbol: 'VED' },
  VEF: { desc: 'Venezuelan Bolívar Fuerte', symbol: 'VEF' },
  VES: { desc: 'Sovereign Bolivar', symbol: 'VES' },
  VET: { desc: 'VeChain', symbol: 'VET' },
  VND: { desc: 'Vietnamese Dong', symbol: '₫' },
  VUV: { desc: 'Vanuatu Vatu', symbol: 'Vt' },
  WAVES: { desc: 'Waves', symbol: 'WAVES' },
  WEMIX: { desc: 'WEMIX', symbol: 'WEMIX' },
  WOO: { desc: 'WOO Network', symbol: 'WOO' },
  WST: { desc: 'Samoan Tala', symbol: 'WS$' },
  XAF: { desc: 'CFA Franc BEAC', symbol: 'FCFA' },
  XAG: { desc: 'Silver (troy ounce)', symbol: 'XAG' },
  XAU: { desc: 'Gold (troy ounce)', symbol: 'XAU' },
  XAUT: { desc: 'Tether Gold', symbol: 'XAUT' },
  XBT: { desc: 'Bitcoin', symbol: 'XBT' },
  XCD: { desc: 'East Caribbean Dollar', symbol: 'EC$' },
  XCG: { desc: 'Xchange', symbol: 'XCG' },
  XCH: { desc: 'Chia', symbol: 'XCH' },
  XDC: { desc: 'XDC Network', symbol: 'XDC' },
  XDR: { desc: 'Special Drawing Rights', symbol: 'SDR' },
  XEC: { desc: 'eCash', symbol: 'XEC' },
  XEM: { desc: 'NEM', symbol: 'XEM' },
  XLM: { desc: 'Stellar Lumen', symbol: 'XLM' },
  XMR: { desc: 'Monero', symbol: 'XMR' },
  XOF: { desc: 'CFA Franc BCEAO', symbol: 'CFA' },
  XPD: { desc: 'Palladium (troy ounce)', symbol: 'XPD' },
  XPF: { desc: 'CFP Franc', symbol: 'CFPF' },
  XPT: { desc: 'Platinum (troy ounce)', symbol: 'XPT' },
  XRP: { desc: 'Ripple', symbol: 'XRP' },
  XTZ: { desc: 'Tezos', symbol: 'XTZ' },
  YER: { desc: 'Yemeni Rial', symbol: '﷼' },
  ZAR: { desc: 'South African Rand', symbol: 'R' },
  ZEC: { desc: 'Zcash', symbol: 'ZEC' },
  ZIL: { desc: 'Zilliqa', symbol: 'ZIL' },
  ZMK: { desc: 'Zambian Kwacha (pre-2013)', symbol: 'ZMK' },
  ZMW: { desc: 'Zambian Kwacha', symbol: 'ZMW' },
  ZWD: { desc: 'Zimbabwean Dollar (old)', symbol: 'Z$' },
  ZWG: { desc: 'Zimbabwe Gold', symbol: 'ZiG' },
  ZWL: { desc: 'Zimbabwean Dollar', symbol: 'ZWL' },
};

// 환율을 저장하는 인터페이스
export interface CurrencyExchangeRates {
  [key: string]: string;
}
