name: qcalc
version: '0.11.3'
summary: Q Calc - Advanced Calculator
description: |
  Q Calc is an advanced calculator application built with Quasar Framework and Electron.
  Features include scientific calculations, unit conversions, and more.

base: core22
confinement: strict
grade: stable

apps:
  qcalc:
    command: bin/desktop-launch $SNAP/qcalc
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - browser-support
      - network
      - network-bind
      - home
    desktop: usr/share/applications/qcalc.desktop

parts:
  qcalc:
    plugin: nodejs
    source: .
    nodejs-version: 20.11.1
    nodejs-package-manager: yarn
    build-packages:
      - npm
      - yarn
    override-build: |
      yarn install
      yarn build
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps
      cp snap/gui/qcalc.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/
      cp assets/qcalc_icon_v2.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps/qcalc.png
    stage-packages:
      - libnss3
      - libnspr4
      - libasound2
      - libgconf-2-4
      - libnotify4
      - libxss1
      - libxtst6
      - xdg-utils
      - libatspi2.0-0
      - libdrm2
      - libgbm1
      - libxcb-dri3-0
